name: flutter_jailbreak_detection_plus_example
description: Demonstrates how to use the flutter_jailbreak_detection_plus plugin.
author: Yazan Al-Kamsheh <yazan.alkamsheh2@Gmail.com>
homepage: https://github.com/yazanalkamsheh/flutter_jailbreak_detection_plus.git

version: 1.0.0+1

environment:
  sdk: '>=3.6.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_jailbreak_detection_plus:
    path: ../

flutter:
  uses-material-design: true
